### ISSUE TITLE
A question about readability (and a suggestion)

### ISSUE THREAD

**Issue by lifepillar** [nightsense/snow#1]
Nice colorscheme!

You mention in the Readme W3C and ISO contrast requirements. I am interested in adding an automatic test for readability to Colortemplate. If you have any suggestion on how such a function could be implemented, it would be much appreciated!

PS: Do you know that you can use Colortemplate to generate files in the `autoload` folder, too? if not, check `:help colortemplate-auxfiles`. The advantage is that you can use symbolic names for colors, and they will be interpolated.

**Comment by nightsense** [comment]
Thanks! Maybe I'll actually be satisfied enough with this one that I can stop messing about with colorschemes and focus on doing actual work with vim. :frog: 

I'll give some thought to the readability test function. As for auxfiles, now that you mention it, I do remember reading about them...then totally forgetting about them by the time I decided to add status line themes. So I'll be adding those to the template soon, thanks for the reminder.

**Comment by lifepillar** [comment]
With Colortemplate's current master, after compiling a template, a scratch buffer (for each background) is opened displaying a contrast ratio matrix. Syntax colouring is used to highlight critical values. I would appreciate if you could try it and tell me whether it fits your requirements about testing readability.

**Comment by nightsense** [comment]
Nice! The syntax highlighting makes it clear at a glance. Definitely fits my requirements.

**Comment by lifepillar** [comment]
Yes, I had thought about that, too. I will make that change.
