### ISSUE TITLE
Shell script doesn't change the background color in iterm

### ISSUE THREAD

**Issue by mcchrish** [nightsense/snow#3]
![screen shot 2018-11-12 at 9 40 34 pm](https://user-images.githubusercontent.com/7200153/48350987-ca30b100-e6c3-11e8-92ee-7a0bf3afb266.png)

Compared to https://github.com/mcchrish/iterm-snow which shows how iterm renders the correct background color through direct configuration.

**Comment by nightsense** [comment]
Thanks @mcchrish , I don't have access to iterm right now but I think the problem is fixed ([25a8375](https://github.com/nightsense/snow/commit/25a8375519beb2487d609185070950b646f68f38)), if you get a chance give it a try and let me know.

**Comment by mcchrish** [comment]
@nightsense I've just tested and now it's fixed. Thanks @nightsense
