### ISSUE TITLE
Commnet and plaintext have most same color

### ISSUE THREAD

**Issue by deathrush** [nightsense/snow#7]
Could you please make comment color lighter?

**Comment by nightsense** [comment]
Hi @deathrush , it's true that the colors are similar compared to many other schemes, the reason being that I wanted comment text to have enough contrast to pass the [W3C minimum contrast standard](https://www.w3.org/WAI/WCAG21/quickref/#contrast-minimum), and I don't really want regular text to be any higher contrast than it is.

You can always customize colors in your vimrc, eg: `hi Comment guifg=#707780` for the dark theme, `hi Comment guifg=#8995A3` for the light theme.

**Comment by deathrush** [comment]
Thank you.
